version: "3.9"

services:
  meida_admin_web:
    image: registry.cn-hangzhou.aliyuncs.com/tongts/meida-admin-web:v1 # 生产环境建议用镜像
    networks:
      - shared
    ports:
      - "3000:3000"
    environment:
      DOMUS_API_URL: http://meida-server_domus-api:9002
      USER_SYSTEM_API_URL: http://meida-server_user_system-api:9001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s

networks:
  shared:
    external: true
    name: meida_network
