import * as React from "react";
import ThemeRegistry from "@/components/theme-registry/ThemeRegistry";
import QueryProvider from "@/libs/QueryProvider";
import { ToastProvider } from "@/libs/ToastProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <QueryProvider>
            <ThemeRegistry>{props.children}</ThemeRegistry>
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
